---
- name: Setup second Jenkins instance
  hosts: localhost
  become: yes
  vars:
    jenkins_new_home: /home/ubuntu/finans
    jenkins_new_port: 8084
    jenkins_user: jenkins
    jenkins_group: jenkins
    jenkins_service_name: jenkins2
    
  tasks:
    - name: Ensure Jenkins dependencies are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - openjdk-11-jdk
        - daemon

    - name: Create Jenkins home directory
      file:
        path: "{{ jenkins_new_home }}"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_group }}"
        mode: '0755'

    - name: Copy Jenkins configuration and data
      command: cp -a /var/lib/jenkins/* {{ jenkins_new_home }}/
      ignore_errors: yes

    - name: Create Jenkins systemd service file
      copy:
        dest: /etc/systemd/system/{{ jenkins_service_name }}.service
        content: |
          [Unit]
          Description=Jenkins Continuous Integration Server
          Documentation=http://jenkins-ci.org/
          After=network.target

          [Service]
          ExecStart=/usr/bin/java -Djenkins.install.runSetupWizard=false -jar /usr/share/jenkins/jenkins.war --httpPort={{ jenkins_new_port }} --prefix=/jenkins2 --webroot={{ jenkins_new_home }}/war --httpListenAddress=0.0.0.0 --jenkins-home={{ jenkins_new_home }}
          User={{ jenkins_user }}
          Group={{ jenkins_group }}
          Type=simple
          Restart=on-failure
          RestartSec=10
          SuccessExitStatus=143

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start the second Jenkins service
      systemd:
        name: "{{ jenkins_service_name }}"
        enabled: yes
        state: started

